name: Sync Google Drive folder and commit

on:
  workflow_dispatch: {}
  schedule:
    # KST 08:00-09:00 (UTC 23:00-00:00) 5분마다 실행
    - cron: "*/5 23,0 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js 설치 및 종속성 설치
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run sync script
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          DEST_DIR: content
        run: |
          npm run sync-gdrive

      - name: Process content to pages
        run: |
          npm run process-content

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(sync): update from Google Drive folder"
            git push
          else
            echo "No changes to commit."
          fi